spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/42ggong
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate.ddl-auto: create

#logging:
#  level:
#    root: debug
#    org:
#      springframework:
#        security: DEBUG